language: julia
julia:
  - 0.6
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Restful"); Pkg.test("Restful", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Restful")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
